### ISSUE TITLE
Detecting Model inside template

### ISSUE THREAD

**Issue by ghost** [danielfone/rails4-custom-scaffold-test#1]
I've found an issue in the question of form customization. Assume I'm using neo4j and I have the following model:

class Contact 
  include Neo4j::ActiveNode
  property :first_name, type: String
  property :surname, type: String
  property :email, type: String
  property :phones, type: String
  has_one :in, :address, type: :HAS_ADDRESS
  has_one :in, :title, type: :HAS_TITLE
  has_one :in, :gender, type: :HAS_GENDER
end

As you may see, I have three relations (:address, :title and :gender). Two of them (:title and :gender) fit for this case you showed, i.e., they must appear as a select box. The first one, :address, must be hidden in my form. It will be rendered in an appropriate partial. 

I haven't found a way to deal with this at scaffold time.

a) If I try to generate the model first to add some methods like **displayable?** or **selectable?**, scaffolding will overwrite it and I'll receive a NameError during scaffolding;

b) I tried f.to_model inside my **lib/templates/erb/scaffold/_form.html.rb**, but it doesn't work. 

Have you ever dealt with this situation, @danielfone ?

**Comment by danielfone** [comment]
@EdDeAlmeidaJr sorry, I have not. To be honest, I haven't used scaffolding much recently. All the best with your efforts, and thanks for getting in touch. :smile:
